# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.29)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS SeQuant::SeQuant-bliss SeQuant::SeQuant)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target SeQuant::SeQuant-bliss
add_library(SeQuant::SeQuant-bliss STATIC IMPORTED)

set_target_properties(SeQuant::SeQuant-bliss PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SEQUANT_USE_SYSTEM_BOOST_HASH=1"
  INTERFACE_LINK_LIBRARIES "range-v3;Boost::headers;Boost::container;Boost::container_hash"
)

# Create imported target SeQuant::SeQuant
add_library(SeQuant::SeQuant STATIC IMPORTED)

set_target_properties(SeQuant::SeQuant PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SEQUANT_CONTEXT_MANIPULATION_THREADSAFE;SEQUANT_ASSERT_BEHAVIOR_=IGNORE;SEQUANT_HAS_EXECUTION_HEADER;SEQUANT_USE_SYSTEM_BOOST_HASH=1"
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_INCLUDE_DIRECTORIES "/home/runner/work/SeQuant/SeQuant;/home/runner/work/SeQuant/SeQuant/_codeql_build_dir"
  INTERFACE_LINK_LIBRARIES "range-v3;Boost::regex;Boost::locale;Boost::headers;SeQuant::SeQuant-bliss;Threads::Threads;\$<LINK_ONLY:libperm::libperm>;\$<LINK_ONLY:>;polymorphic_variant::polymorphic_variant;Boost::container;Boost::container_hash;Boost::hana;Boost::multiprecision;Boost::numeric_conversion;Boost::numeric_interval;Boost::range;Boost::spirit"
)

# Import target "SeQuant::SeQuant-bliss" for configuration "Release"
set_property(TARGET SeQuant::SeQuant-bliss APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SeQuant::SeQuant-bliss PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/runner/work/SeQuant/SeQuant/_codeql_build_dir/libSeQuant-bliss.a"
  )

# Import target "SeQuant::SeQuant" for configuration "Release"
set_property(TARGET SeQuant::SeQuant APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SeQuant::SeQuant PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/runner/work/SeQuant/SeQuant/_codeql_build_dir/libSeQuant.a"
  )

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "range-v3" "Boost::headers" "Boost::container" "Boost::container_hash" "Boost::regex" "Boost::locale" "libperm::libperm" "polymorphic_variant::polymorphic_variant" "Boost::hana" "Boost::multiprecision" "Boost::numeric_conversion" "Boost::numeric_interval" "Boost::range" "Boost::spirit" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
