#ifndef SEQUANT_CORE_EXPORT_TAPP_HPP
#define SEQUANT_CORE_EXPORT_TAPP_HPP

#include <SeQuant/core/export/context.hpp>
#include <SeQuant/core/export/generator.hpp>
#include <SeQuant/core/export/reordering_context.hpp>
#include <SeQuant/core/export/utils.hpp>
#include <SeQuant/core/expr.hpp>
#include <SeQuant/core/index.hpp>
#include <SeQuant/core/rational.hpp>
#include <SeQuant/core/space.hpp>
#include <SeQuant/core/utility/macros.hpp>
#include <SeQuant/core/utility/string.hpp>

#include <cstddef>
#include <map>
#include <optional>
#include <set>
#include <sstream>
#include <string>
#include <string_view>
#include <tuple>
#include <vector>

namespace sequant {

/// The scalar type of the tensors and variables in code generated by the
/// TAPPGenerator
enum class TAPPScalarType {
  /// `double` (`TAPP_F64`)
  Real,
  /// `double complex` (`TAPP_C64`)
  Complex,
};

/// Context class for the TAPPGenerator
class TAPPGeneratorContext : public ReorderingContext {
 public:
  using TagMap = std::map<IndexSpace, std::string>;
  using DimMap = std::map<IndexSpace, std::string>;

  TAPPGeneratorContext() : ReorderingContext(MemoryLayout::RowMajor) {}
  ~TAPPGeneratorContext() = default;

  /// @returns The tag used to name tensor blocks involving the given space.
  /// Defaults to the (sanitized) base key of the space.
  std::string get_tag(const IndexSpace &space) const;
  /// @returns The name of the field in the generated dimension struct that
  /// holds the extent of the given space. Defaults to `dim_<tag>`.
  std::string get_dim(const IndexSpace &space) const;
  /// @returns The concatenated tags of all index slots of the given tensor
  std::string get_tags(const Tensor &tensor) const;

  void set_tag(const IndexSpace &space, std::string tag);
  void set_dim(const IndexSpace &space, std::string dim);

  /// @returns The prefix used for all global names in the generated code
  const std::string &prefix() const;
  void set_prefix(std::string prefix);

  TAPPScalarType scalar_type() const;
  void set_scalar_type(TAPPScalarType type);

 protected:
  TagMap m_index_tags;
  DimMap m_index_dims;
  std::string m_prefix = "sequant";
  TAPPScalarType m_scalar_type = TAPPScalarType::Real;
};

/// Generator for producing C code using the Tensor Algebra Processing
/// Primitives (TAPP) interface
/// - https://github.com/TAPPorg/reference-implementation
///
/// The generated translation unit is self-contained (C11 plus `tapp.h`) and
/// follows TAPP's describe -> plan -> execute split:
/// - `<prefix>_create_plans()` creates one `TAPP_tensor_info` per distinct
///   tensor block shape and one `TAPP_tensor_product` per distinct contraction
///   and stores them in a `<prefix>_plans` struct;
/// - `<prefix>_compute()` (or, for named sections, `<prefix>_<section>()`)
///   only executes these plans and may be called any number of times;
/// - `<prefix>_destroy_plans()` releases all TAPP objects.
///
/// Tensors are brought into and out of memory via caller-provided `load` and
/// `store` callbacks (`<prefix>_io`), mirroring the load/persist semantics of
/// the export framework.
template <typename Context = TAPPGeneratorContext>
class TAPPGenerator : public Generator<Context> {
 public:
  TAPPGenerator() = default;
  ~TAPPGenerator() = default;

  std::string get_format_name() const override { return "C (TAPP)"; }

  bool supports_named_sections() const override { return true; }

  bool requires_named_sections() const override { return false; }

  bool supports_index_batching() const override { return false; }

  DeclarationScope index_declaration_scope() const override {
    return DeclarationScope::Global;
  }

  DeclarationScope variable_declaration_scope() const override {
    return DeclarationScope::Section;
  }

  DeclarationScope tensor_declaration_scope() const override {
    return DeclarationScope::Section;
  }

  PrunableScalars prunable_scalars() const override {
    return PrunableScalars::All;
  }

  std::string represent(const Index &idx, const Context &) const override {
    auto it = m_index_names.find(idx);
    if (it == m_index_names.end()) {
      throw Exception("Index '" + toUtf8(idx.full_label()) +
                      "' has not been declared");
    }

    return it->second;
  }

  std::string represent(const Tensor &tensor,
                        const Context &ctx) const override {
    std::string name = detail::sanitize_identifier(
        tensor.label(), detail::NonAsciiPolicy::Escape);

    if (tensor.num_indices() > 0) {
      name += "_" + ctx.get_tags(tensor);
    }

    return avoid_reserved(std::move(name));
  }

  std::string represent(const Variable &variable,
                        const Context &) const override {
    return avoid_reserved(detail::sanitize_identifier(
        variable.label(), detail::NonAsciiPolicy::Escape));
  }

  std::string represent(const Constant &constant,
                        const Context &ctx) const override {
    const auto &value = constant.value();

    if (value.imag() == 0) {
      return real_literal(value.real());
    }

    if (ctx.scalar_type() != TAPPScalarType::Complex) {
      throw Exception(
          "Complex constants require TAPPScalarType::Complex in the "
          "TAPPGeneratorContext");
    }

    return "CMPLX(" + real_literal(value.real()) + ", " +
           real_literal(value.imag()) + ")";
  }

  std::string represent(const Power &power, const Context &ctx) const override {
    m_uses_math = true;

    const ExprPtr &base = power.base();
    std::string repr =
        ctx.scalar_type() == TAPPScalarType::Complex ? "cpow(" : "pow(";
    repr +=
        scalar_expr(*base, ctx) + ", " + real_literal(power.exponent()) + ")";

    return power.conjugated() ? conj(std::move(repr), ctx) : repr;
  }

  void create(const Tensor &tensor, bool zero_init,
              const Context &ctx) override {
    allocate(tensor, zero_init, ctx);
  }

  void load(const Tensor &tensor, bool set_to_zero,
            const Context &ctx) override {
    allocate(tensor, set_to_zero, ctx);

    if (!set_to_zero) {
      const std::string name = represent(tensor, ctx);
      emit_macro_call(macro("LOAD") + "(\"" + name + "\", " + name + ", " +
                      size_of(tensor, ctx) + ");");
      current().uses_io = true;
    }
  }

  void set_to_zero(const Tensor &tensor, const Context &ctx) override {
    const std::string name = represent(tensor, ctx);
    ensure_local(tensor, ctx);
    emit("memset(" + name + ", 0, " + size_of(tensor, ctx) + " * sizeof *" +
         name + ");");
  }

  void unload(const Tensor &tensor, const Context &ctx) override {
    const std::string name = represent(tensor, ctx);
    current().allocated.erase(name);
    emit("free(" + name + ");");
    emit(name + " = NULL;");
  }

  void destroy(const Tensor &tensor, const Context &ctx) override {
    unload(tensor, ctx);
  }

  void persist(const Tensor &tensor, const Context &ctx) override {
    const std::string name = represent(tensor, ctx);
    emit_macro_call(macro("STORE") + "(\"" + name + "\", " + name + ", " +
                    size_of(tensor, ctx) + ");");
    current().uses_io = true;

    // Persisting implies dropping the in-memory copy
    unload(tensor, ctx);
  }

  void create(const Variable &variable, bool zero_init,
              const Context &ctx) override {
    ensure_local(variable, ctx);
    if (zero_init) {
      set_to_zero(variable, ctx);
    }
  }

  void load(const Variable &variable, bool set_to_zero,
            const Context &ctx) override {
    ensure_local(variable, ctx);
    if (set_to_zero) {
      this->set_to_zero(variable, ctx);
      return;
    }

    const std::string name = represent(variable, ctx);
    emit_macro_call(macro("LOAD") + "(\"" + name + "\", &" + name + ", 1);");
    current().uses_io = true;
  }

  void set_to_zero(const Variable &variable, const Context &ctx) override {
    emit(represent(variable, ctx) + " = 0;");
  }

  void unload(const Variable &, const Context &) override {}

  void destroy(const Variable &, const Context &) override {}

  void persist(const Variable &variable, const Context &ctx) override {
    const std::string name = represent(variable, ctx);
    emit_macro_call(macro("STORE") + "(\"" + name + "\", &" + name + ", 1);");
    current().uses_io = true;
  }

  void compute(const Expr &expression, const Tensor &result,
               const Context &ctx) override {
    ensure_local(result, ctx);
    emit_product(expression, &result, represent(result, ctx), ctx);
  }

  void compute(const Expr &expression, const Variable &result,
               const Context &ctx) override {
    ensure_local(result, ctx);
    emit_product(expression, nullptr, represent(result, ctx), ctx);
  }

  void declare(const Index &idx, const Context &) override {
    if (idx.has_proto_indices()) {
      throw Exception("Proto Indices are not (yet) supported!");
    }

    std::string name = upper_prefix() + "_IDX_" +
                       detail::sanitize_identifier(
                           idx.full_label(), detail::NonAsciiPolicy::Escape);
    if (m_index_name_set.contains(name)) {
      std::size_t suffix = 2;
      while (m_index_name_set.contains(name + "_" + std::to_string(suffix))) {
        ++suffix;
      }
      name += "_" + std::to_string(suffix);
    }

    m_index_name_set.insert(name);
    m_index_names.emplace(idx, std::move(name));
  }

  void declare(const Variable &variable, UsageSet,
               const Context &ctx) override {
    ensure_local(variable, ctx);
  }

  void declare(const Tensor &tensor, UsageSet, const Context &ctx) override {
    ensure_local(tensor, ctx);
  }

  void all_indices_declared(std::size_t, const Context &) override {}

  void all_variables_declared(std::size_t, const Context &) override {}

  void all_tensors_declared(std::size_t, const Context &) override {}

  void begin_declarations(DeclarationScope scope, const Context &ctx) override {
    if (scope == DeclarationScope::Section && !m_in_function) {
      // Code outside of a named section goes into the default function
      begin_function(ctx.prefix() + "_compute");
    }
  }

  void end_declarations(DeclarationScope, const Context &) override {}

  void insert_comment(const std::string &comment, const Context &) override {
    emit(c_comment(comment));
  }

  void begin_named_section(std::string_view name, const Context &ctx) override {
    begin_function(ctx.prefix() + "_" +
                   detail::sanitize_identifier(toUtf16(name),
                                               detail::NonAsciiPolicy::Escape));
  }

  void end_named_section(std::string_view, const Context &) override {
    m_in_function = false;
  }

  void begin_expression(const Context &) override {
    if (!current().body.empty()) {
      current().body += "\n";
    }
  }

  void end_expression(const Context &) override {}

  void begin_export(const Context &ctx) override {
    m_generated.clear();
    m_prefix = ctx.prefix();
    m_scalar_type = ctx.scalar_type();
    m_layout = ctx.memory_layout();
    m_index_names.clear();
    m_index_name_set.clear();
    m_infos.clear();
    m_dims.clear();
    m_plans.clear();
    m_plan_ids.clear();
    m_functions.clear();
    m_in_function = false;
    m_uses_math = false;
  }

  void end_export(const Context &) override {
    std::string &out = m_generated;

    out += "/* Generated by SeQuant */\n\n";
    if (m_scalar_type == TAPPScalarType::Complex) {
      out += "#include <complex.h>\n";
    }
    if (m_uses_math) {
      out += "#include <math.h>\n";
    }
    out += "#include <stddef.h>\n";
    out += "#include <stdint.h>\n";
    out += "#include <stdlib.h>\n";
    out += "#include <string.h>\n\n";
    out += "#include <tapp.h>\n\n";

    emit_types();
    emit_macros();
    emit_create_plans();
    emit_destroy_plans();

    for (const Function &function : m_functions) {
      emit_function(function);
    }

    // Drop the blank line after the last function
    SEQUANT_ASSERT(out.ends_with("\n\n"));
    out.pop_back();
  }

  std::string get_generated_code() const override { return m_generated; }

 protected:
  /// A TAPP_tensor_info in the generated plans struct, shared by all tensors of
  /// the same block shape
  struct TensorInfo {
    std::vector<std::string> dims;
  };

  /// A TAPP_tensor_product in the generated plans struct. Operand B is absent
  /// for unary operations.
  struct Plan {
    std::string info_A;
    std::vector<std::string> idx_A;
    std::string info_B;
    std::vector<std::string> idx_B;
    std::string info_D;
    std::vector<std::string> idx_D;
    std::string description;

    auto key() const {
      return std::tie(info_A, idx_A, info_B, idx_B, info_D, idx_D);
    }
  };

  /// A generated execution function
  struct Function {
    std::string name;
    std::vector<std::string> buffers;
    std::vector<std::string> scalars;
    std::set<std::string> locals;
    /// Buffers that are allocated at the current point of the function
    std::set<std::string> allocated;
    std::string body;
    bool uses_io = false;
    bool uses_tapp = false;
    bool jumps = false;
  };

  std::string m_generated;
  std::string m_prefix;
  TAPPScalarType m_scalar_type = TAPPScalarType::Real;
  MemoryLayout m_layout = MemoryLayout::RowMajor;
  std::map<Index, std::string> m_index_names;
  std::set<std::string> m_index_name_set;
  std::map<std::string, TensorInfo> m_infos;
  std::set<std::string> m_dims;
  std::vector<Plan> m_plans;
  std::map<std::tuple<std::string, std::vector<std::string>, std::string,
                      std::vector<std::string>, std::string,
                      std::vector<std::string>>,
           std::size_t>
      m_plan_ids;
  std::vector<Function> m_functions;
  bool m_in_function = false;
  mutable bool m_uses_math = false;

  static std::string avoid_reserved(std::string name) {
    // Names used by the generated code itself (and `I` from complex.h)
    static const std::set<std::string> reserved = {
        "I",     "alpha",  "error",       "io",  "one",
        "plans", "status", "tapp_status", "dims"};

    if (reserved.contains(name)) {
      name += "_";
    }

    return name;
  }

  static std::string c_comment(std::string_view text) {
    std::string comment(text);
    for (std::size_t pos = comment.find("*/"); pos != std::string::npos;
         pos = comment.find("*/", pos)) {
      comment.replace(pos, 2, "* /");
    }

    return "/* " + comment + " */";
  }

  static std::string real_literal(const rational &value) {
    std::stringstream sstream;
    sstream << numerator(value) << ".0";

    if (denominator(value) != 1) {
      std::stringstream fraction;
      fraction << "(" << sstream.str() << " / " << denominator(value) << ".0)";
      return fraction.str();
    }

    return sstream.str();
  }

  std::string upper_prefix() const {
    std::string upper = m_prefix;
    for (char &c : upper) {
      if (c >= 'a' && c <= 'z') {
        c = static_cast<char>(c - 'a' + 'A');
      }
    }

    return upper;
  }

  std::string macro(std::string_view name) const {
    return upper_prefix() + "_" + std::string(name);
  }

  std::string scalar_type_name() const {
    return m_scalar_type == TAPPScalarType::Complex ? "double complex"
                                                    : "double";
  }

  std::string conj(std::string repr, const Context &ctx) const {
    if (ctx.scalar_type() == TAPPScalarType::Complex) {
      return "conj(" + std::move(repr) + ")";
    }

    // Conjugation is the identity for real scalars
    return repr;
  }

  Function &current() {
    SEQUANT_ASSERT(m_in_function);
    SEQUANT_ASSERT(!m_functions.empty());
    return m_functions.back();
  }

  void begin_function(std::string name) {
    for (const Function &function : m_functions) {
      if (function.name == name) {
        throw Exception("Duplicate function name '" + name +
                        "' in generated TAPP code");
      }
    }

    m_functions.emplace_back();
    m_functions.back().name = std::move(name);
    m_in_function = true;
  }

  void emit(std::string_view line) {
    current().body += "  ";
    current().body += line;
    current().body += "\n";
  }

  /// Emits a line invoking one of the generated macros, all of which jump to
  /// the cleanup label on error
  void emit_macro_call(std::string_view line) {
    emit(line);
    current().jumps = true;
  }

  void ensure_local(const Tensor &tensor, const Context &ctx) {
    std::string name = represent(tensor, ctx);
    if (current().locals.insert(name).second) {
      current().buffers.push_back(std::move(name));
    }
    register_info(tensor, ctx);
  }

  void ensure_local(const Variable &variable, const Context &ctx) {
    std::string name = represent(variable, ctx);
    if (current().locals.insert(name).second) {
      current().scalars.push_back(std::move(name));
    }
  }

  /// Registers the TAPP_tensor_info describing the given tensor's block
  /// @returns The name of that info in the plans struct (without `info_`)
  std::string register_info(const Tensor &tensor, const Context &ctx) {
    std::string name =
        tensor.num_indices() == 0 ? "scalar" : ctx.get_tags(tensor);

    TensorInfo info;
    for (const Index &idx : tensor.const_indices()) {
      info.dims.push_back(ctx.get_dim(idx.space()));
    }

    auto [it, inserted] = m_infos.emplace(name, info);
    if (!inserted && it->second.dims != info.dims) {
      throw Exception("Tensor blocks with tags '" + name +
                      "' have different dimensions; make sure every index "
                      "space has a unique tag");
    }

    m_dims.insert(info.dims.begin(), info.dims.end());

    return name;
  }

  std::string register_scalar_info() {
    m_infos.emplace("scalar", TensorInfo{});
    return "scalar";
  }

  std::string size_of(const Tensor &tensor, const Context &ctx) {
    return "plans->size_" + register_info(tensor, ctx);
  }

  void allocate(const Tensor &tensor, bool zero, const Context &ctx) {
    ensure_local(tensor, ctx);
    const std::string name = represent(tensor, ctx);

    [[maybe_unused]] const bool newly_allocated =
        current().allocated.insert(name).second;
    SEQUANT_ASSERT(newly_allocated);

    emit_macro_call(macro(zero ? "ALLOCATE_ZERO" : "ALLOCATE") + "(" + name +
                    ", " + size_of(tensor, ctx) + ");");
  }

  std::vector<std::string> index_labels(const Tensor &tensor,
                                        const Context &ctx) const {
    std::vector<std::string> labels;
    for (const Index &idx : tensor.const_indices()) {
      labels.push_back(represent(idx, ctx));
    }
    return labels;
  }

  /// @param name The name to use for the tensor (defaults to its label)
  std::string describe(const Tensor &tensor,
                       std::optional<std::string> name = {}) const {
    std::string description = name.value_or(toUtf8(tensor.label())) + "[";
    bool first = true;
    for (const Index &idx : tensor.const_indices()) {
      if (!first) {
        description += ", ";
      }
      description += toUtf8(idx.full_label());
      first = false;
    }
    return description + "]";
  }

  /// @returns A C expression for the given purely scalar expression
  std::string scalar_expr(const Expr &expr, const Context &ctx) const {
    if (expr.is<Constant>()) {
      return represent(expr.as<Constant>(), ctx);
    } else if (expr.is<Variable>()) {
      const Variable &variable = expr.as<Variable>();
      std::string repr = represent(variable, ctx);
      return variable.conjugated() ? conj(std::move(repr), ctx) : repr;
    } else if (expr.is<Power>()) {
      return represent(expr.as<Power>(), ctx);
    } else if (expr.is<Product>()) {
      const Product &product = expr.as<Product>();
      std::vector<std::string> factors;
      if (!product.scalar().is_identity()) {
        factors.push_back(represent(Constant(product.scalar()), ctx));
      }
      for (const ExprPtr &factor : product) {
        factors.push_back(scalar_expr(*factor, ctx));
      }
      return join(factors, " * ", "1.0");
    } else if (expr.is<Sum>()) {
      std::vector<std::string> summands;
      for (const ExprPtr &summand : expr.as<Sum>()) {
        summands.push_back(scalar_expr(*summand, ctx));
      }
      return "(" + join(summands, " + ", "0.0") + ")";
    }

    throw Exception("Unsupported expression type '" + expr.type_name() +
                    "' in scalar context of the TAPP generator");
  }

  static std::string join(const std::vector<std::string> &parts,
                          std::string_view separator, std::string_view empty) {
    if (parts.empty()) {
      return std::string(empty);
    }

    std::string joined = parts.front();
    for (std::size_t i = 1; i < parts.size(); ++i) {
      joined += separator;
      joined += parts[i];
    }
    return joined;
  }

  /// Splits the given product-like expression into its tensor factors and a C
  /// expression for the product of all scalar factors
  void split_factors(const Expr &expr, std::vector<const Tensor *> &tensors,
                     std::vector<std::string> &scalars,
                     const Context &ctx) const {
    if (expr.is<Tensor>()) {
      tensors.push_back(&expr.as<Tensor>());
    } else if (expr.is<Product>()) {
      const Product &product = expr.as<Product>();
      if (!product.scalar().is_identity()) {
        scalars.push_back(represent(Constant(product.scalar()), ctx));
      }
      for (const ExprPtr &factor : product) {
        split_factors(*factor, tensors, scalars, ctx);
      }
    } else {
      scalars.push_back(scalar_expr(expr, ctx));
    }
  }

  static bool contains_tensor(const Expr &expr) {
    if (expr.is<Tensor>()) {
      return true;
    }
    for (const ExprPtr &child : expr) {
      if (contains_tensor(*child)) {
        return true;
      }
    }
    return false;
  }

  /// Emits code for `result += expression`
  /// @param result The result tensor or nullptr if the result is a variable
  /// @param result_name The C name of the result
  void emit_product(const Expr &expression, const Tensor *result,
                    const std::string &result_name, const Context &ctx) {
    if (!contains_tensor(expression)) {
      if (result) {
        throw Exception("The TAPP generator can't assign a scalar to a tensor");
      }
      emit(result_name + " += " + scalar_expr(expression, ctx) + ";");
      return;
    }

    std::vector<const Tensor *> tensors;
    std::vector<std::string> scalars;
    split_factors(expression, tensors, scalars, ctx);

    if (tensors.size() > 2) {
      throw Exception(
          "The TAPP generator only supports unary and binary tensor "
          "operations");
    }
    SEQUANT_ASSERT(!tensors.empty());

    Plan plan;
    plan.info_A = register_info(*tensors[0], ctx);
    plan.idx_A = index_labels(*tensors[0], ctx);
    if (tensors.size() == 2) {
      plan.info_B = register_info(*tensors[1], ctx);
      plan.idx_B = index_labels(*tensors[1], ctx);
    } else {
      plan.info_B = register_scalar_info();
    }
    if (result) {
      plan.info_D = register_info(*result, ctx);
      plan.idx_D = index_labels(*result, ctx);
    } else {
      plan.info_D = register_scalar_info();
    }

    // Plans may be shared by different tensors of the same blocks, so they
    // are described in terms of these blocks
    plan.description = (result ? describe(*result, plan.info_D) : "scalar") +
                       " += " + describe(*tensors[0], plan.info_A);
    if (tensors.size() == 2) {
      plan.description += " " + describe(*tensors[1], plan.info_B);
    }

    std::string operands = describe(*tensors[0]);
    if (tensors.size() == 2) {
      operands += " " + describe(*tensors[1]);
    }
    const std::string target = result ? describe(*result) : result_name;

    std::size_t plan_id = m_plans.size() + 1;
    if (auto [it, inserted] = m_plan_ids.emplace(plan.key(), plan_id);
        !inserted) {
      plan_id = it->second;
    } else {
      m_plans.push_back(std::move(plan));
    }

    const std::string alpha = join(scalars, " * ", "");
    std::string comment = target + " += ";
    if (!alpha.empty()) {
      comment += alpha + " ";
    }
    comment += operands;

    const std::string operand_A = represent(*tensors[0], ctx);
    const std::string operand_B =
        tensors.size() == 2 ? represent(*tensors[1], ctx) : "&one";
    const std::string operand_D = result ? result_name : "&" + result_name;

    current().uses_tapp = true;
    emit(c_comment(comment));
    std::string indent;
    if (!alpha.empty()) {
      emit("{");
      emit("  const " + scalar_type_name() + " alpha = " + alpha + ";");
      indent = "  ";
    }
    const std::string call = macro("CHECK") + "(TAPP_execute_product(";
    emit_macro_call(indent + call + "plans->plan_" + std::to_string(plan_id) +
                    ", plans->exec, &tapp_status,");
    emit(indent + std::string(call.size(), ' ') +
         (alpha.empty() ? "&one" : "&alpha") + ", " + operand_A + ", " +
         operand_B + ", &one, " + operand_D + ", " + operand_D + "));");
    if (!alpha.empty()) {
      emit("}");
    }
  }

  void emit_types() {
    const std::string upper = upper_prefix();
    const std::string scalar = scalar_type_name();
    std::string &out = m_generated;

    out += "typedef enum {\n";
    out += "  " + upper + "_SUCCESS = 0,\n";
    out += "  " + upper + "_TAPP_FAILURE,\n";
    out += "  " + upper + "_OUT_OF_MEMORY,\n";
    out += "  " + upper + "_IO_FAILURE\n";
    out += "} " + m_prefix + "_status;\n\n";

    out +=
        "/* Caller-provided storage of tensors and variables, identified by "
        "name. Both\n";
    out += "   callbacks transfer count elements and return 0 on success. */\n";
    out += "typedef struct {\n";
    out += "  int (*load)(void *user, const char *name, " + scalar +
           " *buffer, size_t count);\n";
    out += "  int (*store)(void *user, const char *name, const " + scalar +
           " *buffer, size_t count);\n";
    out += "  void *user;\n";
    out += "} " + m_prefix + "_io;\n\n";

    if (!m_index_names.empty()) {
      // Enumerators are ordered by index, not by name
      out += "/* Mode labels */\n";
      out += "enum {\n";
      std::size_t i = 0;
      for (const auto &[idx, name] : m_index_names) {
        out += "  " + name;
        out += ++i < m_index_names.size() ? ",\n" : "\n";
      }
      out += "};\n\n";
    }

    out += "/* Extents of the index spaces */\n";
    out += "typedef struct {\n";
    if (m_dims.empty()) {
      out += "  int unused; /* no index spaces are used */\n";
    }
    for (const std::string &dim : m_dims) {
      out += "  int64_t " + dim + ";\n";
    }
    out += "} " + m_prefix + "_dims;\n\n";

    out += "typedef struct {\n";
    out += "  " + m_prefix + "_dims dims;\n";
    out += "  TAPP_handle handle;\n";
    out += "  TAPP_executor exec;\n";
    out += "  /* Layout and number of elements of each tensor block */\n";
    for (const auto &[name, info] : m_infos) {
      out += "  TAPP_tensor_info info_" + name + ";\n";
      out += "  size_t size_" + name + ";\n";
    }
    if (!m_plans.empty()) {
      out += "  /* Tensor operations */\n";
    }
    for (std::size_t i = 0; i < m_plans.size(); ++i) {
      out += "  TAPP_tensor_product plan_" + std::to_string(i + 1) + "; " +
             c_comment(m_plans[i].description) + "\n";
    }
    out += "} " + m_prefix + "_plans;\n\n";
  }

  void emit_macros() {
    const std::string upper = upper_prefix();
    std::string &out = m_generated;

    const auto define = [&](std::string_view signature,
                            const std::vector<std::string> &body) {
      out += "#define " + upper + "_" + std::string(signature) + " \\\n";
      out += "  do { \\\n";
      for (const std::string &line : body) {
        out += "    " + line + " \\\n";
      }
      out += "  } while (0)\n\n";
    };
    const auto fail = [&](std::string_view status) {
      return std::vector<std::string>{
          "  status = " + upper + "_" + std::string(status) + ";",
          "  goto cleanup;", "}"};
    };
    const auto concat = [](std::vector<std::string> lhs,
                           const std::vector<std::string> &rhs) {
      lhs.insert(lhs.end(), rhs.begin(), rhs.end());
      return lhs;
    };

    out +=
        "/* Error handling: the macros below expect the enclosing function "
        "to have the\n";
    out += "   variables status and error as well as a cleanup label. */\n";
    define("CHECK(call)", concat({"TAPP_error tapp_error_ = (call);",
                                  "if (!TAPP_check_success(tapp_error_)) {",
                                  "  if (error) *error = tapp_error_;"},
                                 fail("TAPP_FAILURE")));
    define("ALLOCATE(buffer, count)",
           concat({"(buffer) = malloc((count) * sizeof *(buffer));",
                   "if (!(buffer)) {"},
                  fail("OUT_OF_MEMORY")));
    define("ALLOCATE_ZERO(buffer, count)",
           concat({"(buffer) = calloc((count), sizeof *(buffer));",
                   "if (!(buffer)) {"},
                  fail("OUT_OF_MEMORY")));
    define("LOAD(name, buffer, count)",
           concat({"if (io->load(io->user, (name), (buffer), (count)) != 0) {"},
                  fail("IO_FAILURE")));
    define(
        "STORE(name, buffer, count)",
        concat({"if (io->store(io->user, (name), (buffer), (count)) != 0) {"},
               fail("IO_FAILURE")));
  }

  void emit_create_plans() {
    std::string &out = m_generated;

    const bool any_modes = [&] {
      for (const auto &[name, info] : m_infos) {
        if (!info.dims.empty()) {
          return true;
        }
      }
      return false;
    }();

    if (any_modes) {
      out += "/* Computes the strides of a dense ";
      out += m_layout == MemoryLayout::ColumnMajor ? "column" : "row";
      out += "-major tensor and returns its number of elements */\n";
      out += "static size_t " + m_prefix +
             "_layout(int nmode, const int64_t *extents, int64_t *strides)\n";
      out += "{\n";
      out += "  size_t size = 1;\n";
      if (m_layout == MemoryLayout::ColumnMajor) {
        out += "  for (int i = 0; i < nmode; ++i) {\n";
      } else {
        out += "  for (int i = nmode - 1; i >= 0; --i) {\n";
      }
      out += "    strides[i] = (int64_t)size;\n";
      out += "    size *= (size_t)extents[i];\n";
      out += "  }\n";
      out += "  return size;\n";
      out += "}\n\n";
    }

    const std::string datatype =
        m_scalar_type == TAPPScalarType::Complex ? "TAPP_C64" : "TAPP_F64";
    const std::string check = macro("CHECK");

    out += "void " + m_prefix + "_destroy_plans(" + m_prefix +
           "_plans *plans);\n\n";

    out +=
        "/* Creates all TAPP objects needed by the compute functions. On "
        "failure, nothing\n";
    out +=
        "   needs to be destroyed and, unless error is NULL, *error holds "
        "the failing TAPP\n";
    out += "   error code. */\n";
    out += m_prefix + "_status " + m_prefix + "_create_plans(" + m_prefix +
           "_plans *plans, const " + m_prefix +
           "_dims *dims, TAPP_error *error)\n";
    out += "{\n";
    out += "  " + m_prefix + "_status status = " + upper_prefix() +
           "_SUCCESS;\n\n";
    out += "  memset(plans, 0, sizeof *plans);\n";
    out += "  plans->dims = *dims;\n";
    out += "  " + check + "(TAPP_create_handle(&plans->handle));\n";
    out += "  " + check + "(TAPP_create_executor(&plans->exec));\n";

    for (const auto &[name, info] : m_infos) {
      const std::string field = "plans->info_" + name;
      const std::string nmode = std::to_string(info.dims.size());
      out += "\n";
      if (info.dims.empty()) {
        out += "  " + check + "(TAPP_create_tensor_info(&" + field + ", " +
               datatype + ", 0, NULL, NULL));\n";
        out += "  plans->size_" + name + " = 1;\n";
        continue;
      }

      std::vector<std::string> extents;
      for (const std::string &dim : info.dims) {
        extents.push_back("dims->" + dim);
      }

      out += "  {\n";
      out += "    const int64_t extents[" + nmode + "] = {" +
             join(extents, ", ", "") + "};\n";
      out += "    int64_t strides[" + nmode + "];\n";
      out += "    plans->size_" + name + " = " + m_prefix + "_layout(" + nmode +
             ", extents, strides);\n";
      out += "    " + check + "(TAPP_create_tensor_info(&" + field + ", " +
             datatype + ", " + nmode + ", extents, strides));\n";
      out += "  }\n";
    }

    for (std::size_t i = 0; i < m_plans.size(); ++i) {
      const Plan &plan = m_plans[i];
      out += "\n  {\n";
      out += "    " + c_comment(plan.description) + "\n";

      const auto labels = [&](std::string_view name,
                              const std::vector<std::string> &idx) {
        if (idx.empty()) {
          return std::string("NULL");
        }
        out += "    static const int64_t " + std::string(name) + "[] = {" +
               join(idx, ", ", "") + "};\n";
        return std::string(name);
      };
      const std::string idx_A = labels("idx_A", plan.idx_A);
      const std::string idx_B = labels("idx_B", plan.idx_B);
      const std::string idx_D = labels("idx_D", plan.idx_D);

      const std::string call = "    " + check + "(TAPP_create_tensor_product(";
      const std::string indent(call.size(), ' ');
      out +=
          call + "&plans->plan_" + std::to_string(i + 1) + ", plans->handle,\n";
      out += indent + "TAPP_IDENTITY, plans->info_" + plan.info_A + ", " +
             idx_A + ",\n";
      out += indent + "TAPP_IDENTITY, plans->info_" + plan.info_B + ", " +
             idx_B + ",\n";
      out += indent + "TAPP_IDENTITY, plans->info_" + plan.info_D + ", " +
             idx_D + ",\n";
      out += indent + "TAPP_IDENTITY, plans->info_" + plan.info_D + ", " +
             idx_D + ",\n";
      out += indent + "TAPP_DEFAULT_PREC));\n";
      out += "  }\n";
    }

    out += "\n  return status;\n\n";
    out += "cleanup:\n";
    out += "  " + m_prefix + "_destroy_plans(plans);\n";
    out += "  return status;\n";
    out += "}\n\n";
  }

  void emit_destroy_plans() {
    std::string &out = m_generated;

    out +=
        "/* Releases all TAPP objects of plans (which may be only partially "
        "created) */\n";
    out +=
        "void " + m_prefix + "_destroy_plans(" + m_prefix + "_plans *plans)\n";
    out += "{\n";
    for (std::size_t i = m_plans.size(); i > 0; --i) {
      const std::string field = "plans->plan_" + std::to_string(i);
      out +=
          "  if (" + field + ") TAPP_destroy_tensor_product(" + field + ");\n";
    }
    for (auto it = m_infos.rbegin(); it != m_infos.rend(); ++it) {
      const std::string field = "plans->info_" + it->first;
      out += "  if (" + field + ") TAPP_destroy_tensor_info(" + field + ");\n";
    }
    out += "  if (plans->exec) TAPP_destroy_executor(plans->exec);\n";
    out += "  if (plans->handle) TAPP_destroy_handle(plans->handle);\n";
    out += "  memset(plans, 0, sizeof *plans);\n";
    out += "}\n\n";
  }

  void emit_function(const Function &function) {
    std::string &out = m_generated;
    const std::string scalar = scalar_type_name();

    out += m_prefix + "_status " + function.name + "(const " + m_prefix +
           "_plans *plans, const " + m_prefix + "_io *io, TAPP_error *error)\n";
    out += "{\n";
    out +=
        "  " + m_prefix + "_status status = " + upper_prefix() + "_SUCCESS;\n";
    if (function.uses_tapp) {
      out += "  const " + scalar + " one = 1.0;\n";
      out += "  TAPP_status tapp_status = 0;\n";
    }
    for (const std::string &buffer : function.buffers) {
      out += "  " + scalar + " *" + buffer + " = NULL;\n";
    }
    for (const std::string &variable : function.scalars) {
      out += "  " + scalar + " " + variable + " = 0;\n";
    }
    if (!function.uses_io) {
      out += "  (void)io;\n";
    }
    if (!function.uses_tapp) {
      out += "  (void)error;\n";
    }
    if (function.buffers.empty() && !function.uses_tapp) {
      out += "  (void)plans;\n";
    }
    out += "\n";
    out += function.body;
    out += "\n";
    if (function.jumps) {
      out += "cleanup:\n";
    }
    for (const std::string &buffer : function.buffers) {
      out += "  free(" + buffer + ");\n";
    }
    out += "  return status;\n";
    out += "}\n\n";
  }
};

}  // namespace sequant

#endif  // SEQUANT_CORE_EXPORT_TAPP_HPP
