# Generated by BoostInstall.cmake for boost_numeric_interval-1.84.0

include(CMakeFindDependencyMacro)

if(NOT boost_config_FOUND)
  find_dependency(boost_config 1.84.0 EXACT)
endif()
if(NOT boost_detail_FOUND)
  find_dependency(boost_detail 1.84.0 EXACT)
endif()
if(NOT boost_logic_FOUND)
  find_dependency(boost_logic 1.84.0 EXACT)
endif()

include("${CMAKE_CURRENT_LIST_DIR}/boost_numeric_interval-targets.cmake")
