# Generated by BoostInstall.cmake for boost_tti-1.84.0

include(CMakeFindDependencyMacro)

if(NOT boost_config_FOUND)
  find_dependency(boost_config 1.84.0 EXACT)
endif()
if(NOT boost_function_types_FOUND)
  find_dependency(boost_function_types 1.84.0 EXACT)
endif()
if(NOT boost_mpl_FOUND)
  find_dependency(boost_mpl 1.84.0 EXACT)
endif()
if(NOT boost_preprocessor_FOUND)
  find_dependency(boost_preprocessor 1.84.0 EXACT)
endif()
if(NOT boost_type_traits_FOUND)
  find_dependency(boost_type_traits 1.84.0 EXACT)
endif()

include("${CMAKE_CURRENT_LIST_DIR}/boost_tti-targets.cmake")
