# Generated by BoostInstall.cmake for boost_align-1.84.0

include(CMakeFindDependencyMacro)

if(NOT boost_assert_FOUND)
  find_dependency(boost_assert 1.84.0 EXACT)
endif()
if(NOT boost_config_FOUND)
  find_dependency(boost_config 1.84.0 EXACT)
endif()
if(NOT boost_core_FOUND)
  find_dependency(boost_core 1.84.0 EXACT)
endif()
if(NOT boost_static_assert_FOUND)
  find_dependency(boost_static_assert 1.84.0 EXACT)
endif()

include("${CMAKE_CURRENT_LIST_DIR}/boost_align-targets.cmake")
