# Generated by BoostInstall.cmake for boost_pool-1.84.0

include(CMakeFindDependencyMacro)

if(NOT boost_assert_FOUND)
  find_dependency(boost_assert 1.84.0 EXACT)
endif()
if(NOT boost_config_FOUND)
  find_dependency(boost_config 1.84.0 EXACT)
endif()
if(NOT boost_integer_FOUND)
  find_dependency(boost_integer 1.84.0 EXACT)
endif()
if(NOT boost_throw_exception_FOUND)
  find_dependency(boost_throw_exception 1.84.0 EXACT)
endif()
if(NOT boost_type_traits_FOUND)
  find_dependency(boost_type_traits 1.84.0 EXACT)
endif()
if(NOT boost_winapi_FOUND)
  find_dependency(boost_winapi 1.84.0 EXACT)
endif()

include("${CMAKE_CURRENT_LIST_DIR}/boost_pool-targets.cmake")
