#include "processing_step.hpp"

#include <SeQuant/core/utility/exception.hpp>

#include <string>

namespace sequant::util::extint {

ProcessingStep::~ProcessingStep() = default;

namespace detail {

std::optional<std::string_view> strip_autogenerated_id(std::string_view id) {
  if (auto pos = id.find('.'); pos != std::string_view::npos) {
    // Remove step ID of previous step
    id = id.substr(pos);
  }

  if (id.empty() ||
      id.substr(1).find_first_not_of("0123456789") == std::string_view::npos) {
    // "Trivial" (autogenerated) IDs aren't worth preserving as aliases
    return std::nullopt;
  }

  return id;
}

std::string make_output_range_id(std::string_view step_id, std::size_t start,
                                 std::size_t count) {
  return std::string(step_id) + "[" + std::to_string(start) + "-" +
         std::to_string(start + count - 1) + "]";
}

void alias_individual_ids(ExecutionContext &ctx, std::string_view step_id,
                          const std::vector<std::string_view> &associated_ids,
                          std::string_view target_id) {
  for (std::string_view assoc_id : associated_ids) {
    std::optional<std::string_view> suffix = strip_autogenerated_id(assoc_id);
    if (!suffix) {
      continue;
    }

    std::string alias = std::string(step_id) + std::string(*suffix);

    if (ctx.has_data(alias)) {
      if (!ctx.ids_are_equivalent(target_id, alias)) {
        throw Exception("Duplicate ID name '" + std::string(*suffix) +
                        "' leading to ambiguity for '" + alias + "'");
      }

      continue;
    }

    ctx.add_data_alias(target_id, std::move(alias));
  }
}

}  // namespace detail

}  // namespace sequant::util::extint
