#ifndef SEQUANT_EXTERNAL_INTERFACE_PROCESSINGSTEP_HPP
#define SEQUANT_EXTERNAL_INTERFACE_PROCESSINGSTEP_HPP

#include "execution_context.hpp"

#include <SeQuant/core/expr.hpp>
#include <SeQuant/core/meta.hpp>
#include <SeQuant/core/utility/exception.hpp>
#include <SeQuant/core/utility/macros.hpp>

#include <nlohmann/json_fwd.hpp>

#include <concepts>
#include <string>
#include <string_view>
#include <vector>

namespace sequant::util::extint {

class ProcessingStep {
 public:
  ProcessingStep() = default;
  virtual ~ProcessingStep();

  virtual std::string kind() const = 0;

  virtual bool accepts_options() const = 0;
  virtual bool requires_options() const = 0;
  virtual void set_options(const nlohmann::json &options) = 0;

  virtual std::size_t run(std::string_view step_id, ExecutionContext &ctx,
                          const std::vector<std::string_view> &inputs = {}) = 0;
};

namespace detail {

template <typename DataType>
class OBOProcessFunctionMember {
 protected:
  virtual std::size_t process(std::string_view id_prefix, std::size_t id_start,
                              ExecutionContext &ctx, const DataType &data) = 0;
};

template <>
class OBOProcessFunctionMember<void> {
 protected:
  virtual std::size_t process(std::string_view id_prefix, std::size_t id_start,
                              ExecutionContext &ctx) = 0;
};

}  // namespace detail

/// The main point of this wrapper is to
/// 1) Hide the loop over inputs from steps that only process one input at a
///    time without needing access to the other inputs while doing so
/// 2) Propagate output aliases. That is, if the inputs are aliased as
///   'input.bla', we want the associated outputs to be aliased to
///   'output.bla' to allow easy referencing in the driver. This applies to
///   individual as well as group aliases.
template <typename DataType>
class OneByOneProcessingStep
    : public ProcessingStep,
      public detail::OBOProcessFunctionMember<DataType> {
 public:
  std::size_t run(std::string_view step_id, ExecutionContext &ctx,
                  const std::vector<std::string_view> &inputs = {}) override {
    std::size_t total_outputs = 0;

    if constexpr (std::same_as<DataType, void>) {
      if (!inputs.empty()) {
        throw Exception(kind() + " doesn't take any inputs");
      }

      try {
        total_outputs = this->process(step_id, total_outputs, ctx);
      } catch (const std::exception &e) {
        throw Exception("Error while processing " + kind() + ": " + e.what());
      }
    } else {
      std::map<std::string_view, std::vector<std::string>> group_assocs;

      for (std::string_view current_input : inputs) {
        for (const ExecutionContext::Data<ProcessingData> &current :
             ctx.get_data(current_input)) {
          const DataType &data = convert_data<DataType>(current.data.get());

          SEQUANT_ASSERT(!current.associated_ids.empty());

          std::size_t new_outputs;
          try {
            new_outputs = this->process(step_id, total_outputs, ctx, data);
          } catch (const std::exception &e) {
            throw Exception("Error in " + kind() + " on input " +
                            std::string(current.associated_ids.front()) + ": " +
                            e.what());
          }

          if (new_outputs == 0 && alias_unchanged_inputs()) {
            new_outputs = 1;
            ctx.add_data_alias(
                current.associated_ids.front(),
                std::string(step_id) + "." + std::to_string(total_outputs));
          }

          if (new_outputs > 0) {
            std::string created_outputs =
                std::string(step_id) + "[" + std::to_string(total_outputs) +
                "-" + std::to_string(total_outputs + new_outputs - 1) + "]";

            for (std::string_view assoc_id : current.associated_ids) {
              if (auto pos = assoc_id.find('.');
                  pos != std::string_view::npos) {
                // Remove step ID of previous step
                assoc_id = assoc_id.substr(pos);
              }

              if (assoc_id.empty() ||
                  assoc_id.substr(1).find_first_not_of("0123456789") ==
                      std::string_view::npos) {
                // Skip "trivial" (autogenerated) IDs
                continue;
              }

              std::string alias = std::string(step_id) + std::string(assoc_id);

              if (ctx.has_data(alias)) {
                if (!ctx.ids_are_equivalent(created_outputs, alias)) {
                  throw Exception("Duplicate ID name '" +
                                  std::string(assoc_id) +
                                  "' leading to ambiguity for '" + alias + "'");
                }

                continue;
              }

              ctx.add_data_alias(created_outputs, std::move(alias));
            }

            for (std::string_view group_id : current.associated_group_ids) {
              group_assocs[group_id].emplace_back(created_outputs);
            }
          }

          total_outputs += new_outputs;
        }
      }

      for (auto &[group_id, assoc_outputs] : group_assocs) {
        const std::size_t expected_size = ctx.dataset_size(group_id);
        SEQUANT_ASSERT(expected_size >= assoc_outputs.size());

        if (expected_size != assoc_outputs.size()) {
          continue;
        }

        std::string out_group_id;
        if (auto pos = group_id.find('.'); pos != std::string_view::npos) {
          // Remove previous step ID
          out_group_id =
              std::string(step_id) + std::string(group_id.substr(pos));
        } else {
          out_group_id = std::string(step_id) + "." + std::string(group_id);
        }

        if (ctx.has_data(out_group_id)) {
          if (!ctx.ids_are_equivalent(assoc_outputs, out_group_id)) {
            throw Exception(
                "Duplicate group ID name '" + std::string(group_id) +
                "' leading to ambiguity for '" + out_group_id + "'");
          }

          continue;
        }

        ctx.add_data_alias(assoc_outputs, std::move(out_group_id));
      }
    }

    return total_outputs;
  }

 protected:
  virtual bool alias_unchanged_inputs() const { return false; }
};

}  // namespace sequant::util::extint

#endif  // SEQUANT_EXTERNAL_INTERFACE_PROCESSINGSTEP_HPP
