// Generated by tests/unit/tools/dump_ga_reference.py from the Python prototype
// chain (proto_csv_core/sched/opt/flat, per_term_opt_dp) -- exact reference
// numbers for the PAO-CCSD-DF f-only and g-only E+R1 universes under the
// prototype cost convention (merges cost 2x the extent product, additions
// cost the face size; flat composite extents |i|=180 |mu~|=1000 |K|=3000
// |a<i>|=100 |a<i,j>|=50). Do not edit by hand.
#ifndef SEQUANT_TESTS_GA_REFERENCE_HPP
#define SEQUANT_TESTS_GA_REFERENCE_HPP

#include <cstddef>
#include <vector>

namespace ga_reference {

struct {
  const char* name = "fonly";
  std::size_t n_terms = 7;
  std::size_t n_nodes = 33;
  std::size_t n_keys = 216;
  std::size_t key_pairs = 309;
  std::vector<double> per_term_opt = {36036000, 597600000, 496800000, 432000000, 36000000, 7038000000, 7038000000};
  double l2_flat = 90000;
  double base_a = 15674526000;
  std::vector<int> g_opt = {0, 2, 0, 1, 2, 4, 4, 5, 0, 1, 2, 3, 0, 1, 2, 0, 0, 2, 4, 6, 8, 0, 2, 4, 6, 8};
  std::vector<int> h0 = {0, 0, 0, 0, 0};
  double seed_greedy = 11427336000;
  double seed_exact = 11427336000;
  std::vector<int> g_ctrl = {0, 1, 0, 1, 2, 4, 4, 5, 0, 1, 1, 3, 0, 1, 2, 0, 0, 2, 4, 6, 8, 0, 2, 4, 6, 8};
  std::vector<int> h_ctrl = {0, 2, 2, 4, 4};
  double control_exact = 7645532400;
  double control_greedy = 7645532400;
} fonly;

struct {
  const char* name = "gonly";
  std::size_t n_terms = 24;
  std::size_t n_nodes = 180;
  std::size_t n_keys = 3020;
  std::size_t key_pairs = 7528;
  std::vector<double> per_term_opt = {19602162000000, 19602162000000, 388872036000, 2232006000, 7548000000, 20682036000000, 9234000000, 389433600000, 20682036000000, 19796896800000, 395874000000, 1807200000, 1274472000000, 2793600000, 9234000000, 19796896800000, 229924800000, 2232000000, 12082356000000, 395874000000, 12276792000000, 1468908000000, 12082356000000, 12276792000000};
  double l2_flat = 342003;
  double base_a = 173458925184003;
  std::vector<int> g_opt = {0, 2, 4, 6, 0, 2, 4, 6, 0, 1, 4, 6, 8, 0, 1, 4, 3, 4, 0, 1, 4, 6, 4, 10, 0, 2, 2, 6, 8, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 4, 4, 5, 4, 7, 8, 0, 2, 2, 6, 8, 0, 1, 2, 4, 4, 7, 6, 11, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 4, 4, 5, 6, 0, 1, 2, 3, 0, 1, 2, 4, 4, 5, 9, 11, 8, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 4, 4, 7, 6, 11, 0, 1, 2, 4, 4, 5, 6, 0, 1, 2, 3, 0, 1, 4, 6, 8, 10, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 6, 6, 7, 0, 1, 4, 3, 4, 10, 0, 1, 4, 6, 8, 10, 0, 1, 2, 3, 4, 6, 6, 7};
  std::vector<int> h0 = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
  double seed_greedy = 49629908262003;
  std::vector<int> winner_g = {0, 1, 3, 3, 0, 2, 1, 5, 0, 1, 4, 6, 4, 0, 0, 4, 3, 4, 0, 1, 4, 3, 4, 10, 0, 2, 2, 6, 8, 0, 1, 2, 4, 4, 8, 6, 6, 0, 1, 2, 4, 4, 5, 4, 7, 7, 0, 2, 0, 6, 8, 0, 1, 2, 4, 4, 5, 6, 11, 0, 1, 2, 4, 4, 4, 6, 7, 0, 1, 2, 4, 4, 5, 6, 0, 1, 2, 2, 0, 1, 2, 4, 4, 5, 9, 7, 8, 0, 1, 2, 4, 5, 8, 6, 7, 0, 1, 2, 4, 4, 7, 6, 11, 0, 1, 2, 4, 4, 5, 5, 0, 1, 2, 3, 0, 1, 3, 3, 8, 10, 0, 1, 2, 4, 4, 5, 5, 6, 0, 1, 2, 3, 4, 8, 6, 7, 0, 1, 4, 3, 4, 10, 0, 1, 2, 3, 8, 10, 0, 1, 2, 3, 4, 8, 6, 7};
  std::vector<int> winner_h = {0, 2, 3, 0, 1, 2, 1, 8, 5, 5, 0, 0, 9, 9, 11, 0, 22, 14, 14, 17, 17, 18};
  double winner_total = 33091289023202;
  double winner_l1 = 31616906766000;
  double winner_l2 = 1474382257202;
  std::size_t winner_n_arrays = 25;
} gonly;

}  // namespace ga_reference

#endif
